version: '3.1'

services:
  web:
    build: .
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public
    links:
      - mongodb
      - redis

  mongodb:
    build: ./docker/mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
