version: '3.1'

services:
  web:
    build: ./web-app
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./web-app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/public
    depends_on:
      - mongodb
      - redis

  api:
    build: ./api-server
    restart: always
    command: node app
    ports:
      - "1337:1337"
    volumes:
      - ./api-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis    
  
  mongodb:
    build: ./docker/mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
